name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to create'
        required: false

jobs:
  build_and_test:
    runs-on: macos-latest
    name: Build and test
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      
    - name: Install lld-link
      run: |
        brew install llvm
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        
    - name: Install xwin
      run: cargo install --locked xwin
      
    - name: Setup Windows SDK
      run: |
        mkdir -p $HOME/.local/share/xwin-sdk
        xwin --accept-license splat --output $HOME/.local/share/xwin-sdk
        
    - name: Build (CI)
      if: ${{ github.event.inputs.version == '' }}
      run: dotnet build -t:Pack src/PublishAotCrossXWin.macOS.nuproj
      
    - name: Build (CD)
      if: ${{ github.event.inputs.version != '' }}
      run: dotnet build -t:Pack src/PublishAotCrossXWin.macOS.nuproj -p:Version=${{ github.event.inputs.version }}
      
    - name: Build test binary
      run: dotnet publish -r win-x64 -c Release test/Hello.csproj
      
    - name: Upload test binary
      uses: actions/upload-artifact@v4
      with:
        name: Hello
        path: test/bin/Release/net9.0/win-x64/publish/Hello.exe
        
    - name: Archive NuGet
      if: ${{ github.event.inputs.version != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: PublishAotCrossXWin.macOS.${{ github.event.inputs.version }}.nupkg
        path: src/bin/Debug/PublishAotCrossXWin.macOS.${{ github.event.inputs.version }}.nupkg

  validate:
    needs: build_and_test
    runs-on: windows-latest
    name: Try launching
    
    steps:
    - name: Download test binary
      uses: actions/download-artifact@v4
      with:
        name: Hello
        
    - name: Launch
      run: ./Hello.exe
